### ISSUE TITLE
500 on live site

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#62]
```
2019-11-21T14:00:08.686647936Z app[web.1]: Traceback (most recent call last):
2019-11-21T14:00:08.686720456Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
2019-11-21T14:00:08.686735748Z app[web.1]:     response = self.full_dispatch_request()
2019-11-21T14:00:08.686808129Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
2019-11-21T14:00:08.686825368Z app[web.1]:     rv = self.handle_user_exception(e)
2019-11-21T14:00:08.686867396Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
2019-11-21T14:00:08.686889498Z app[web.1]:     reraise(exc_type, exc_value, tb)
2019-11-21T14:00:08.686927338Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2019-11-21T14:00:08.686938681Z app[web.1]:     raise value
2019-11-21T14:00:08.686983310Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
2019-11-21T14:00:08.686995033Z app[web.1]:     rv = self.dispatch_request()
2019-11-21T14:00:08.687051357Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
2019-11-21T14:00:08.687063940Z app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2019-11-21T14:00:08.687103420Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/dash/dash.py", line 1289, in dispatch
2019-11-21T14:00:08.687114429Z app[web.1]:     response.set_data(self.callback_map[output]['callback'](*args))
2019-11-21T14:00:08.687162954Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/dash/dash.py", line 1173, in add_context
2019-11-21T14:00:08.687174110Z app[web.1]:     output_value = func(*args, **kwargs)  # %% callback invoked %%
2019-11-21T14:00:08.687222653Z app[web.1]:   File "/app/apps/heatmap.py", line 134, in update_heatmap
2019-11-21T14:00:08.687234270Z app[web.1]:     title = get_chart_title(numerators, denominators, result_filter, entity_names)
2019-11-21T14:00:08.687280546Z app[web.1]:   File "/app/apps/base.py", line 64, in get_chart_title
2019-11-21T14:00:08.687302264Z app[web.1]:     map(get_test_name, denominators)
2019-11-21T14:00:08.688460367Z app[web.1]: KeyError: 'all'
```

**Comment by evansd** [comment]
Will be fixed as part of the general refactor of title generation that I'm working on

**Comment by sebbacon** [comment]
Have just pushed a quick one now as I want to show people

**Comment by sebbacon** [comment]
In 39e09dd1d3f1348d0efd7c2b2da4c40f08237693
